version: "3.9"

services:
  barcam:
    build: .
    container_name: barcam_web
    restart: always

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.routers.barcam.rule=Host(`www.barcam.site`)"
      - "traefik.http.routers.barcam.entrypoints=websecure"
      - "traefik.http.routers.barcam.tls=true"
      - "traefik.http.routers.barcam.tls.certresolver=mi-resuelves-ssl"

      - "traefik.http.services.barcam.loadbalancer.server.port=3001"

networks:
  traefik-public:
    external: true